name: Morning Weather

on:
  schedule:
    - cron: '0 22 * * *' # 日本時間 朝7:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests
      - name: Run
        env:
          KAROTTER_ID: ${{ secrets.KAROTTER_ID }}
          KAROTTER_PW: ${{ secrets.KAROTTER_PW }}
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }} # ここをOWMに合わせました
        run: python main.py
