name: Morning Weather

on:
  schedule:
    - cron: '0 22 * * *' # JST 7:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          # python -m を使うのが最も確実です
          python -m pip install --upgrade pip
          python -m pip install requests
          python -m pip install git+https://github.com/kav0tter/KarotterPy.git
          
      - name: Check files
        run: ls -R  # ファイルが本当にあるかログに表示させる（デバッグ用）

      - name: Run
        env:
          KAROTTER_API_KEY: ${{ secrets.KAROTTER_API_KEY }}
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
        run: python main.py
